flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
allow-different-user: true
packages:
- '.'
- location:
    git: https://github.com/mchaver/mysql
    commit: 87c8048fe5149ecaf3825b1e05f41ecf25ba051e
extra-deps:
- tf-random-0.5
- QuickCheck-2.8.2
- control-monad-omega-0.3.1
- HTTP-4000.3.3
- HUnit-1.3.1.1
- MissingH-1.4.0.1
- MonadRandom-0.4.2.3
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-0.11.2.0
- aeson-compat-0.3.4.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- asn1-encoding-0.9.4
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.0
- attoparsec-0.13.0.2
- auto-update-0.1.4
- base-compat-0.9.1
- base-orphans-0.5.4
- base-unicode-symbols-0.2.2.4
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- bifunctors-5.3
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.1
- blaze-markup-0.7.0.3
- blaze-textual-0.2.1.0
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.8.1.0
- bytestring-conversion-0.3.1
- case-insensitive-1.2.0.6
- cereal-0.5.2.0
- charset-0.3.7.1
- comonad-5
- conduit-1.2.6.6
- conduit-extra-1.1.13.1
- configurator-0.3.0.0
- connection-0.2.5
- contravariant-1.4
- cookie-0.4.2
- cryptohash-0.11.9
- cryptonite-0.17
- data-default-class-0.1.2.0
- directory-1.2.6.3
- distributive-0.5.0.2
- dlist-0.7.1.2
- double-conversion-2.0.1.0
- easy-file-0.2.1
- either-4.4.1.1
- exceptions-0.8.2.1
- expiring-cache-map-0.0.5.4
- fail-4.9.0.0
- fast-logger-2.4.6
- file-embed-0.0.10
- free-4.12.4
- hashable-1.2.4.0
- hourglass-0.2.10
- hslogger-1.2.10
- http-api-data-0.2.3
- http-client-0.4.30
- http-client-tls-0.2.4.1
- http-date-0.0.6.1
- http-media-0.6.3
- http-types-0.9.1
- http2-1.6.0
- iproute-1.7.0
- kan-extensions-5.0.1
- lens-4.14
- lifted-base-0.2.3.6
- memory-0.13
- mime-types-0.1.0.7
- mmorph-1.0.6
- monad-control-1.0.1.0
- monad-logger-0.3.18
- monad-loops-0.4.3
- mtl-2.2.1
- mysql-simple-0.2.2.5
- nats-1.1.1
- network-2.6.2.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parsec-3.1.11
- path-pieces-0.2.1
- pcre-light-0.4.0.4
- pem-0.2.2
- persistent-2.5
- persistent-mysql-2.5
- persistent-template-2.5.1.3
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- process-1.4.2.0
- profunctors-5.2
- psqueues-0.2.2.1
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resource-pool-0.2.3.2
- resourcet-1.1.7.4
- safe-0.3.9
- scientific-0.3.4.8
- semigroupoids-5.1
- semigroups-0.18.2
- servant-0.7.1
- servant-foreign-0.7.1
- servant-js-0.7.1
- servant-server-0.7.1
- servant-docs-0.7.1
- servant-mock-0.7.1
- servant-client-0.7.1
- lackey-0.3.2
- silently-1.2.5
- simple-sendfile-0.2.25
- socks-0.5.5
- split-0.2.3.1
- stm-2.4.4.1
- stm-chans-3.0.0.4
- streaming-commons-0.1.15.5
- string-conversions-0.4
- stringsearch-0.3.6.6
- syb-0.6
- system-filepath-0.4.13.4
- tagged-0.8.4
- text-1.2.2.1
- time-locale-compat-0.1.1.3
- tls-1.3.8
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.2.0
- unix-time-0.3.6
- unordered-containers-0.2.7.1
- utf8-string-1.0.1.1
- vault-0.3.0.6
- vector-0.11.0.0
- void-0.7.1
- wai-3.2.1.1
- wai-app-static-3.1.5
- wai-cors-0.2.5
- wai-extra-3.0.15.2
- wai-logger-2.2.7
- wai-middleware-static-0.8.0
- warp-3.2.6
- word8-0.1.2
- x509-1.6.3
- x509-store-1.6.1
- x509-system-1.6.3
- x509-validation-1.6.3
- zlib-0.6.1.1
- aeson-pretty-0.8.1
- cmdargs-0.10.14
- filepath-1.4.1.0
- hex-0.1.2
- transformers-0.5.2.0
#- Cabal-1.22.8.0
- Cabal-1.24.0.0
#- mysql-0.1.1.8
resolver: ghc-8.0.1
